#!/usr/bin/env python

import sys, subprocess, os

def main():
  if (len(sys.argv) != 2):
      raise NameError('wrong number of args')

  test_case_file = sys.argv[1]

  fp = open(test_case_file, 'r')
  compile_file = open("L3.input", 'w')
  for line in fp:
      compile_file.write(line)
  compile_file.close()
  fp.close()

  subprocess.check_call(["racket","L3.rkt"], stdout=subprocess.PIPE)

  output_file = open("L3.output", 'r')
  for line in output_file:
      print line,

  os.remove('L3.output')
  os.remove('L3.input')

if __name__ == '__main__':
    main()
